# Generated by Django 4.2.8 on 2023-12-30 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_alter_room_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room", options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="participant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
